### ISSUE TITLE
Searching for videos with queries including hashtags (#) throws an error

### ISSUE THREAD

**Issue by synicalsyntax** [tjrgg/simple-youtube-api#36]
Running the following code:

```js
const YTapi = require('simple-youtube-api');
const youtube = new YTapi(youtubeKey);

async function search(args) {
  const items = await youtube.searchVideos(args, 1);
  console.log(items.length);
} 

search('#JAMINTHEVAN');
```

Throws the following error:
```
{ errors:
   [ { domain: 'global',
       reason: 'required',
       message: 'Required parameter: part',
       locationType: 'parameter',
       location: 'part' } ],
  code: 400,
  message: 'Required parameter: part' }
```

No error is thrown once the `#` is removed from the query. I suppose I could use `%23` as a replacement for the `#` character to eliminate the error, but I think it should be up to the library to sanitize HTTP request parameters.

**Comment by WoodNeck** [comment]
Same here.
Looks like [encodeURI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) in [Request.js line 18](https://github.com/HyperCoder2975/simple-youtube-api/blob/4ec452df066079f0a2f44a5ceed3ee9a3e80f417/src/Request.js#L18) is causing problem, as it won't encode such characters like #, &
I think using [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) instead will fix it.

Also you can override `make` function in Request instance for temporary fix.
Here's an example. I use axios, instead of node-fetch.

```js
const api = new YouTube(global.env.GOOGLE_API_KEY);
// Override previous make function to support escape characters like '#'
api.request.make = function(endpoint, qs = {}) {
	qs = Object.assign({ key: this.youtube.key }, qs);
	return axios.get(`https://www.googleapis.com/youtube/v3/${endpoint}`, {
		params: qs,
	}).then(body => body.data);
};

**Comment by appellation** [comment]
URL encoding all query parameters is not supported by the YouTube API for some reason.

**Comment by WoodNeck** [comment]
Didn't notice that sending multiple part is possible! My mistake.
How about allowing some characters exceptionally then?

I think some characters, especially hashtag('#') won't be used in other parts of parameters.
And it make request to return 400 error, not empty result.
I think it can be confusing to some users.

This can be one of the approaches.
Can replace regex with more exceptional characters. For example, adding '$' and '!' as exceptional characters will result in /[$#!]/g.
```js
// Request.js : line 18
return fetch(
  encodeURI(`https://www.googleapis.com/youtube/v3/${endpoint}${params.length ? `?${params.join('&')}` : ''}`)
    .replace(/[#]/g, c=> `%${c.charCodeAt(0).toString(16}`)
)

**Comment by appellation** [comment]
I would prefer it if the YouTube API wasn't shit and accepted properly URL-encoded query parameters. However, barring that possibility, I'm thinking right now to only encode `q` parameters since I don't believe there are any other query parameters where this will be an issue.
